config/routes.rb
ItaBite::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|ja/ do  

    resources :subcontractors 
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    
    match '/signup', to: 'users#new'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    resources :clients do
      resources :jobs
    end

    resources :machines do
      resources :employees do
        resources :approvals
      end
    end
    
    resources :employees do
      resources :machines do
        resources :approvals
      end
    end

    resources :jobs do
      resources :items
    end

    resources :items do
      resources :operations
      resources :rounds
      resources :squares
      resources :subcontracts
    end

    resources :ingredients do
      resources :changes
    end

  end

end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to :machine
  belongs_to :employee
  has_many :operations
  has_many :items
  attr_accessible :employee_id, :machine_id
end

app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :ingredient
  attr_accessible :count, :total, :add_remove, :created_at

  after_initialize :init

  def init
  	self.add_remove ||=2
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :jobs
  attr_accessible :name

    UNRANSACKABLE_ATTRIBUTES = ["created_at", "updated_at", "id"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :machines, :through => :approvals
  attr_accessible :first_name, :last_name, :machine_ids
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :changes
  attr_accessible :measure1, :measure2, :measure3, :note
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :blue_print_number, :completion, :job_id, :name, :pieces, :identification, :round_square
  has_many :subcontracts
  has_many :operations
  has_many :approvals, :through=>:operations
  has_many :rounds
  has_many :squares
  belongs_to :job
end

app/models/job.rb
class Job < ActiveRecord::Base
  DEFAULT_SEARCH_PARAMETER ={}
  attr_accessible :items_attributes, :actual, :billing, :contact, :description, :in_date, :name, :target, :client_id, :priority
  belongs_to :client
  has_many :items
  accepts_nested_attributes_for :items, :allow_destroy => true

  UNRANSACKABLE_ATTRIBUTES = ["description", "created_at", "updated_at", "client_id", "client"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :employees, :through => :approvals
  attr_accessible :name, :notes, :machine_type, :employee_ids
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  attr_accessible :end, :notes, :start, :item_id, :machine_id, :employee_id, :approval_id
  belongs_to :item
  belongs_to :approval
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :delivery_date, :diameter, :item_id, :length, :material, :order_date, :pieces
  belongs_to :item
end

app/models/square.rb
class Square < ActiveRecord::Base
  attr_accessible :delivery_date, :item_id, :length, :material, :order_date, :pieces, :thickness, :width
  belongs_to :item
end

app/models/subcontract.rb
class Subcontract < ActiveRecord::Base
  belongs_to :item
  belongs_to :subcontractor
  attr_accessible :estimated, :in, :item_id, :notes, :out, :subcontractor_id
end

app/models/subcontractor.rb
class Subcontractor < ActiveRecord::Base
  attr_accessible :name
  has_many :subcontracts, :dependent=>:destroy
  has_many :items, :through=>:subcontracts
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :password, :password_confirmation, :email, :username
  has_secure_password
  
  before_save { |user| user.email=email.downcase}
  before_save :create_remember_token

  validates :username, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: 	true,
  					format: 	{ with: VALID_EMAIL_REGEX},
  					uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence:true 

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/subcontractors_controller.rb
class SubcontractorsController < ApplicationController
	
	def new
		@subcontractor=Subcontractor.new		
	end

	def create
		@subcontractor = Subcontractor.new(params[:subcontractor])
		if @subcontractor.save
			redirect_to @subcontractor
		else
			render 'new'
		end
	end

	def update
		@subcontractor = Subcontractor.find(params[:id]) 
		if @subcontractor.update_attributes(params[:subcontractor])
			redirect_to subcontractor_path(@subcontractor)
		else
			redirect_to subcontractor_path(@subcontractor)
		end
	end

	def edit
		@subcontractor = Subcontractor.find(params[:id]) 
	end

	def destroy
		@subcontractor = Subcontractor.find(params[:id]) 
		@subcontractor.destroy
		redirect_to subcontractors_path
	end

	def index
		@subcontractor = Subcontractor.find(:all)
	end

	def show
		@subcontractor = Subcontractor.find(params[:id])
	end

	private
	    def signed_in_user
	      redirect_to signin_url, notice: "Please sign in" unless signed_in?
	    end 
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/helpers/subcontractors_helper.rb
module SubcontractorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subcontractors/edit.html.erb
<body>
	<div class="row">
		<div class="span7 offset4">
			<legend><%=t :subcontractor_edit %></legend>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6 offset3">
			<%= form_for(@subcontractor, :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					<%=t :subcontractor_name %>
				</label>
				<div class="controls">
					<%= f.text_field :name %>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<%= f.submit t(:submit), :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>

<% end %>

app/views/subcontractors/index.html.erb
<div class="row">
	<div class="span8 offset1">
		<h1><%=t :subcontractors %></h1>
		<%= link_to t(:subcontractor_new),  new_subcontractor_path, {:class => 'btn btn-primary'} %>
		
		<table class="table">
			<thead>
				<tr>
					<th><%=t :subcontractor_name %></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @subcontractor.each do |subcontractor| %>
				<tr>
					<td><%= link_to subcontractor.name, subcontractor %></td>
					<td><%=link_to t(:edit), edit_subcontractor_path(subcontractor)%> <%=link_to t(:delete),subcontractor_path(subcontractor), {:confirm => 'Are you sure?', :method => :delete} %></td>
				</tr>
				<% end %>	
			</tbody>
		</table>
	</div>
</div>

app/views/subcontractors/new.html.erb
<body>
	<div class="row">
		<div class="span7 offset4">
			<legend><%=t :subcontractor_new %></legend>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6 offset3">
			<%= form_for(@subcontractor, :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					<%=t :subcontractor_name %>
				</label>
				<div class="controls">
					<%= f.text_field :name %>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<%= f.submit t(:submit), :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>

<% end %>

app/views/subcontractors/show.html.erb
<div class="row">
	<div class="span6 offset1">
		<h2> <%= @subcontractor.name %></h2>	
		<%= link_to t(:subcontractor_edit),  edit_client_path(@subcontractor), {:class => 'btn btn-primary'} %>
		<%= link_to t(:subcontractor_delete),client_path(@subcontractor), {:confirm => 'Are you sure?', :class => 'btn btn-danger', :method => :delete}  %>
	</div>
</div>

<% if @subcontractor.subcontracts[0] %>
	<div class="row">
		<div class="span6 offset1">
			<h2><%=t :items %></h2>
			<table class ="table"> 
				<thead>
					<tr>
						<th><%=t :job_name %></th>
						<th><%=t :item_id %></th>
						<th><%=t :item_name %></th>
						<th><%=t :item_out %></th>
						<th><%=t :item_estimate %></th>
						<th><%=t :item_in %></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @subcontractor.subcontracts.each do |subcontract| %>
					<tr>
						<td><%=link_to subcontract.item.job.name, subcontract.item.job %></td>
						<td><%=subcontract.item.identification%></td>
						<td><%=subcontract.item.name%></td>
						<td><%=subcontract.out%></td>
						<td><%=subcontract.estimated%></td>
						<td>
							<% if subcontract.in? %>
								<%=subcontract.in%>
							<% else %>
								<%= form_for([subcontract]) do |t| %>
									<%= t.hidden_field :in, :value => Date.today %>
									<%= t.submit t(:subcontract_complete) %>
								<% end %>
							<% end %>
						</td>
						<td>
							<%= link_to t(:edit), edit_subcontract_path(subcontract) %>  <%= link_to t(:delete), subcontract_path(subcontract), :confirm => 'Are you sure?', :method => :delete %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
<% end %>