config/routes.rb
ItaBite::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|ja/ do  

    resources :subcontractors 
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    
    match '/signup', to: 'users#new'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    resources :clients do
      resources :jobs
    end

    resources :machines do
      resources :employees do
        resources :approvals
      end
    end
    
    resources :employees do
      resources :machines do
        resources :approvals
      end
    end

    resources :jobs do
      resources :items
    end

    resources :items do
      resources :operations
      resources :rounds
      resources :squares
      resources :subcontracts
    end

    resources :ingredients do
      resources :changes
    end

  end

end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to :machine
  belongs_to :employee
  has_many :operations
  has_many :items
  attr_accessible :employee_id, :machine_id
end

app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :ingredient
  attr_accessible :count, :total, :add_remove, :created_at

  after_initialize :init

  def init
  	self.add_remove ||=2
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :jobs
  attr_accessible :name

    UNRANSACKABLE_ATTRIBUTES = ["created_at", "updated_at", "id"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :machines, :through => :approvals
  attr_accessible :first_name, :last_name, :machine_ids
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :changes
  attr_accessible :measure1, :measure2, :measure3, :note
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :blue_print_number, :completion, :job_id, :name, :pieces, :identification, :round_square
  has_many :subcontracts
  has_many :operations
  has_many :approvals, :through=>:operations
  has_many :rounds
  has_many :squares
  belongs_to :job
end

app/models/job.rb
class Job < ActiveRecord::Base
  DEFAULT_SEARCH_PARAMETER ={}
  attr_accessible :items_attributes, :actual, :billing, :contact, :description, :in_date, :name, :target, :client_id, :priority
  belongs_to :client
  has_many :items
  accepts_nested_attributes_for :items, :allow_destroy => true

  UNRANSACKABLE_ATTRIBUTES = ["description", "created_at", "updated_at", "client_id", "client"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :employees, :through => :approvals
  attr_accessible :name, :notes, :machine_type, :employee_ids
end

app/models/misc_ingredient.rb
class MiscIngredient < ActiveRecord::Base
  attr_accessible :delivery_date, :description, :item_id, :material, :order_date, :pieces
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  attr_accessible :end, :notes, :start, :item_id, :machine_id, :employee_id, :approval_id
  belongs_to :item
  belongs_to :approval
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :delivery_date, :diameter, :item_id, :length, :material, :order_date, :pieces
  belongs_to :item
end

app/models/square.rb
class Square < ActiveRecord::Base
  attr_accessible :delivery_date, :item_id, :length, :material, :order_date, :pieces, :thickness, :width
  belongs_to :item
end

app/models/subcontract.rb
class Subcontract < ActiveRecord::Base
  belongs_to :item
  belongs_to :subcontractor
  attr_accessible :estimated, :in, :item_id, :notes, :out, :subcontractor_id
end

app/models/subcontractor.rb
class Subcontractor < ActiveRecord::Base
  attr_accessible :name
  has_many :subcontracts, :dependent=>:destroy
  has_many :items, :through=>:subcontracts
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :password, :password_confirmation, :email, :username
  has_secure_password
  
  before_save { |user| user.email=email.downcase}
  before_save :create_remember_token

  validates :username, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: 	true,
  					format: 	{ with: VALID_EMAIL_REGEX},
  					uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence:true 

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	helper_method :sort_column, :sort_direction
	def new
		@job=Job.new		
	end

	def create
		@job = Job.new(params[:job])
		if @job.save
			redirect_to @job
		else
			render 'new'
		end
	end

	def update
		@job = Job.find(params[:id])
		if @job.update_attributes(params[:job])
			redirect_to @job.client
		else
			redirect_to job_path(@job)
		end
	end

	def show
		@job=Job.find(params[:id])
		@item = @job.items.find(:all)

		respond_to do |format|
			format.html
			format.pdf {render :layout => false}
		end
	end

	def index
		@search = Job.search(params[:q])
		@search.build_condition
		@results = @search.result
		@results = @results.where(:actual => nil) unless params[:q]
		@job = @results.paginate(:per_page => 10, :page => params[:page])
	end

	def edit
		@job = Job.find(params[:id])
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy
		redirect_to jobs_path
	end

	private
	def sort_column
		Job.column_names.include?(params[:sort]) ? params[:sort] : "name"
	end
	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_condition_fields.html.erb
<div class="field">
	<div class ="styled-select">
		<%= f.attribute_fields do |a| %>
			<%= a.attribute_select associations: [:client] %>
		<% end %>
		<%= f.predicate_select({only: [:eq]})%>
		<%= f.value_fields do |v| %>
			<%= v.text_field :value %>
		<% end %>
	</div>
</div>

app/views/jobs/_item-fields.html.erb
				<div class="control-group">
					<label class="control-label">
						Name
					</label>
					<div class="controls">
						<%= item_form.text_field :name %>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label">
						Pieces
					</label>
					<div class="controls">
						<%= item_form.text_field :pieces %>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label">
						Blue Print Number
					</label>
					<div class="controls">
						<%= item_form.text_field :blue_print_number %>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label">
						Round/Square
					</label>
					<div class="controls">
						<%= item_form.text_field :round_square %>
					</div>
				</div>
				<%= item_form.link_to_remove "Remove this item" %>

			<% end %>

app/views/jobs/_items.html.erb
<table>
	<th>ID</th>
	<th><%=t :item_name %></th>
	<th><%=t :pieces %></th>
	<th><%=t :item_bp %></th>
	<tbody>
		<% job.items.each do |item| %>
		<tr>
			<td><%=item.identification %></td> 
			<td><%=item.name %></td>
			<td><%=item.pieces %></td>
			<td><%=item.blue_print_number %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/jobs/_jobs.html.erb
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>

		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th><%= sort_link(@search, :name, t(:job_name))%></th>
					<th> <%=t :client %> </th>
					<th><%= sort_link(@search, :contact, t(:contact))%></th>
					<th><%=t :job_billing %></th>
					<th><%= sort_link(@search, :in_date, t(:job_intake))%></th>
					<th><%= sort_link(@search, :target, t(:job_target))%></th>
					<th><%= sort_link(@search, :actual, t(:job_complete))%></th>
				</tr>
			</thead>
			<tbody>
				<% @job.each do |job| %>
				<% if job.target < Date.today %>
					<tr class="error">
				<% elsif job.priority == 2%>
					<tr class="warning">
				<% else %>
					<tr>
				<% end %>
					<td><div class="hide_items">+</div></td>
					<td><%= link_to job.name, job %></td>
					<td><% if job.client %>
							<%= link_to job.client.name, job.client %>
						<% end %>
						</td>
					<td><%=job.contact%></td>
					<td><%= link_to job.billing, job %></td>
					<td><%= job.in_date %></td>
					<td><%= job.target %></td>
					<td><% if job.actual? %>
							<%=job.actual %>
						<% else %>
							<%= form_for(job) do |t| %>
								<%= t.hidden_field :actual, :value => Date.today %>
								<%= t.submit t(:complete) %>
							<% end %>
						<% end %>
					</td>
				</tr>
				<tr class="hidden">
					<td></td>
					<td colspan="6">
						<div class="items"><%= render 'items', :job => job %></div>
					</td>
				</tr>
				<% end %>	
			</tbody>
		</table>

app/views/jobs/_show-item.html.erb
<h2>Items</h2>
			<table class ="table"> 
				<thead>
					<tr>
						<th>ID</th>
						<th><%=t :item_name %></th>
						<th><%=t :pieces %></th>
						<th><%=t :item_bp %></th>
						<th><%=t :round_square %></th>
						<th><%=t :item_complete %></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @item.each do |item| %>
					<tr>
						<td><%=item.identification%></td>
						<td><%= link_to item.name, job_item_path(@job, item) %></td>
						<td><%=item.pieces%></td>
						<td><%=item.blue_print_number%></td>
						<td><%=item.round_square %></td>
						<td>
							<% if item.completion? %>
								<%=item.completion%>
							<% else %>
								<%= form_for([@job,item]) do |t| %>
									<%= t.hidden_field :completion, :value => Date.today %>
									<%= t.submit t(:item_finish) %>
								<% end %>
							<% end %>
						</td>
						<td>
							<%= link_to t(:edit), edit_job_item_path(@job, item) %>  <%= link_to t(:delete), job_item_path(@job, item), :confirm => 'Are you sure?', :method => :delete %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

app/views/jobs/edit.html.erb
<body>
<div class="row">
		<div class="span7 offset4">
			<legend><%=t :job_edit %></legend>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6 offset3">
			<%= form_for(@job, :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					<%=t :job_name %>
				</label>
				<div class="controls">
					<%= f.text_field :name %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :priority %>
				</label>
				<div class="controls">
					<%= f.select(:priority, [[t(:low), 1],[t(:high),2]]) %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :client %>
				</label>
				<div class="controls">
					<%= f.select :client_id, Client.all.collect{|x| [x.name, x.id]}, {} %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :contact %>
				</label>
				<div class="controls">
					<%= f.text_field :contact %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :job_billing %>
				</label>
				<div class="controls">
					<%= f.text_field :billing %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :notes %>
				</label>
				<div class="controls">
					<%= f.text_area :description, :rows => 5 %>
				</div>
			</div>


			<div class="control-group">
				<label class="control-label">
					<%=t :job_intake %>
				</label>
				<div class="controls">
					<%= f.date_select :in_date, :start_year => Time.now.year - 1, :end_year => Time.now.year, :order => [:year, :month, :day]%>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :job_target %>
				</label>
				<div class="controls">
					<%= f.date_select :target, :start_year => Time.now.year, :end_year => Time.now.year + 1, :order => [:year, :month, :day]%>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					:<%=t :job_complete %>
				</label>
				<div class="controls">
					<%= f.date_select :actual, :start_year => Time.now.year - 1 , :end_year => Time.now.year, :order => [:year, :month, :day], :include_blank => true %>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<%= f.submit t(:edit), :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>

<% end %>

app/views/jobs/index.html.erb
<body>
	<div class="row">
	<div class="span8 offset1">
		<h1><%=t :jobs %></h1>
		<%= search_form_for @search do |f| %>
			<%= f.condition_fields do |c| %>
				<%= render "condition_fields", f: c%>
			<% end %>
			<div class="actions"><%= f.submit t(:search), :class => "btn" %></div>
		<% end %>

		<%= link_to t(:add_job),  new_job_path, {:class => 'btn btn-primary'} %>

		<div id="jobs"><%= render 'jobs' %></div>

		<%= will_paginate @job %>
	</div>
	</div>
</body>

app/views/jobs/index.js.erb
    $('#jobs').html('<%= escape_javascript(render("jobs")) %>');  

app/views/jobs/new.html.erb
<body>
<div class="row">
		<div class="span7 offset4">
			<legend><%=t :add_job %></legend>
		</div>
	</div>

	<div class="row">
		<div class="span6 offset3">
			<%= nested_form_for(@job, :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					<%=t :job_name %>
				</label>
				<div class="controls">
					<%= f.text_field :name %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :priority %>
				</label>
				<div class="controls">
					<%= f.select(:priority, [[t(:low), 1],[t(:high),2]]) %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :client %>
				</label>
				<div class="controls">
					<%= f.select :client_id, Client.all.collect{|x| [x.name, x.id]}, {} %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :contact %>
				</label>
				<div class="controls">
					<%= f.text_field :contact %>
				</div>
			</div>


			<div class="control-group">
				<label class="control-label">
					<%=t :job_billing %>
				</label>
				<div class="controls">
					<%= f.text_field :billing %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :notes %>
				</label>
				<div class="controls">
					<%= f.text_area :description, :rows => 5 %>
				</div>
			</div>


			<div class="control-group">
				<label class="control-label">
					<%=t :job_intake %>
				</label>
				<div class="controls">
					<%= f.date_select :in_date, :start_year => Time.now.year - 1, :end_year => Time.now.year, :order => [:year, :month, :day]%>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :job_target %>
				</label>
				<div class="controls">
					<%= f.date_select :target, :start_year => Time.now.year, :end_year => Time.now.year + 1, :order => [:year, :month, :day]%>
				</div>
			</div>

			
			<%= f.fields_for :items do |item_form| %>

				<legend><%=t :item_add %></legend>

				<div class="control-group">
					<label class="control-label">
						ID
					</label>
					<div class="controls">
						<%= item_form.text_field :identification %>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label">
						<%=t :item_name %>
					</label>
					<div class="controls">
						<%= item_form.text_field :name %>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label">
						<%=t :pieces %>
					</label>
					<div class="controls">
						<%= item_form.text_field :pieces %>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label">
						<%=t :item_bp %>
					</label>
					<div class="controls">
						<%= item_form.text_field :blue_print_number %>
					</div>
				</div>

				<div class="control-group">
					<label class="control-label">
						<%=t :round_square %>
					</label>
					<div class="controls">
						<%= item_form.text_field :round_square %>
					</div>
				</div>

				<%= item_form.link_to_remove t(:item_delete) %>


			<% end %>


				<div class="row">
					<%= f.link_to_add t(:item_add), :items %>
				</div>
			

			<div class="control-group">
				<div class="controls">
					<%= f.submit t(:submit), :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>
<% end %>

app/views/jobs/show.html.erb
<body>
	<div class="row">
		<div class="span6 offset1">
			<h2> <%= @job.name %></h2> 					<h4><%= @job.billing %></h4> 
			<h3><% if @job.client %>
				 <%= @job.client.name %>  
				<% end %>
			</h3>
			
			<h4><table class ="table"> 
				<tbody>
					<tr>
						<td><%=t :job_intake %></td>
						<td> <%= @job.in_date %></td>
					</tr>
					<tr>
						<td><%=t :job_target %></td>
						<td> <%= @job.target %></td>
					</tr>
					<% if @job.actual? %>
						<tr>
							<td> <%=t :job_complete %> </td>
							<td> <%= @job.actual %></td>
						</tr>

					<% else %>
						<tr>
							<td></td>
							<td><%= form_for(@job, :remote => true) do |t| %>
								<%= t.hidden_field :actual, :value => Date.today %>
								<%= t.submit "Complete Job" %></td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table></h4>
			<%= link_to t(:item_add),  new_job_item_path(@job), {:class => 'btn btn-primary'} %>
			<%= link_to t(:job_edit),  edit_job_path(@job), {:class => 'btn btn-primary'} %>
			<%= link_to t(:job_delete),job_path(@job), {:confirm => 'Are you sure?', :class => 'btn btn-danger', :method => :delete}  %>
		</div>
	</div>
	<p></p>

	<div class="row">
		<div class="span10 offset1">
			<div id="show-item">
				<%= render "show-item" %>
			</div>
		</div>
	</div>
</body>