config/routes.rb
ItaBite::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|ja/ do  

    resources :subcontractors 
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    
    match '/signup', to: 'users#new'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    resources :clients do
      resources :jobs
    end

    resources :machines do
      resources :employees do
        resources :approvals
      end
    end
    
    resources :employees do
      resources :machines do
        resources :approvals
      end
    end

    resources :jobs do
      resources :items
    end

    resources :items do
      resources :operations
      resources :rounds
      resources :squares
      resources :subcontracts
    end

    resources :ingredients do
      resources :changes
    end

  end

end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to :machine
  belongs_to :employee
  has_many :operations
  has_many :items
  attr_accessible :employee_id, :machine_id
end

app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :ingredient
  attr_accessible :count, :total, :add_remove, :created_at

  after_initialize :init

  def init
  	self.add_remove ||=2
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :jobs
  attr_accessible :name

    UNRANSACKABLE_ATTRIBUTES = ["created_at", "updated_at", "id"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :machines, :through => :approvals
  attr_accessible :first_name, :last_name, :machine_ids
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :changes
  attr_accessible :measure1, :measure2, :measure3, :note
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :blue_print_number, :completion, :job_id, :name, :pieces, :identification, :round_square
  has_many :subcontracts
  has_many :operations
  has_many :approvals, :through=>:operations
  has_many :rounds
  has_many :squares
  belongs_to :job
end

app/models/job.rb
class Job < ActiveRecord::Base
  DEFAULT_SEARCH_PARAMETER ={}
  attr_accessible :items_attributes, :actual, :billing, :contact, :description, :in_date, :name, :target, :client_id, :priority
  belongs_to :client
  has_many :items
  accepts_nested_attributes_for :items, :allow_destroy => true

  UNRANSACKABLE_ATTRIBUTES = ["description", "created_at", "updated_at", "client_id", "client"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :employees, :through => :approvals
  attr_accessible :name, :notes, :machine_type, :employee_ids
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  attr_accessible :end, :notes, :start, :item_id, :machine_id, :employee_id, :approval_id
  belongs_to :item
  belongs_to :approval
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :delivery_date, :diameter, :item_id, :length, :material, :order_date, :pieces
  belongs_to :item
end

app/models/square.rb
class Square < ActiveRecord::Base
  attr_accessible :delivery_date, :item_id, :length, :material, :order_date, :pieces, :thickness, :width
  belongs_to :item
end

app/models/subcontract.rb
class Subcontract < ActiveRecord::Base
  belongs_to :item
  belongs_to :subcontractor
  attr_accessible :estimated, :in, :item_id, :notes, :out, :subcontractor_id
end

app/models/subcontractor.rb
class Subcontractor < ActiveRecord::Base
  attr_accessible :name
  has_many :subcontracts, :dependent=>:destroy
  has_many :items, :through=>:subcontracts
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :password, :password_confirmation, :email, :username
  has_secure_password
  
  before_save { |user| user.email=email.downcase}
  before_save :create_remember_token

  validates :username, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: 	true,
  					format: 	{ with: VALID_EMAIL_REGEX},
  					uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence:true 

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	helper_method :sort_column, :sort_direction
	def new
		@ingredient=Ingredient.new
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
	end

	def index
		@search = Ingredient.search(params[:q])
		@ingredient = @search.result
		@change = Change.new
	end

	def create	
		@ingredient = Ingredient.new(params[:ingredient])
		if @ingredient.save
			redirect_to @ingredient
		else
			render 'new'
		end
	end

	def update
		@ingredient = Ingredient.find(params[:id])
		if @ingredient.update_attributes(params[:ingredient])
			redirect_to ingredient_path(@ingredient)
		else
			render 'edit'
		end
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		@ingredient.destroy
		redirect_to ingredients_path
	end

	def show
		@ingredient = Ingredient.find(params[:id])
		@q = @ingredient.changes.search(params[:q]) 
		@change = @q.result(:distinct => true).order(sort_column + ' ' + sort_direction)
		@direction = sort_direction
		@column = sort_column

	end

	private
	    def sort_column
	    	Change.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
	  	end


		def sort_direction
		  	%w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
		end





end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/_changes.html.erb
<table class="table">
	<thread>
		<tr>
			<th>
				<%= sortable "add_remove", "Add/Remove" %>
				<% if @direction=="asc" and @column=="add_remove" %>
					<i class="icon-arrow-up"></i>
				<% elsif @direction=="desc" and @column=="add_remove" %>
					<i class="icon-arrow-down"></i>
				<% end %>
			</th>
			<th>
				<%= sortable "count", "Number"%>
				<% if @direction=="asc" and @column=="count" %>
					<i class="icon-arrow-up"></i>
				<% elsif @direction=="desc" and @column=="count" %>
					<i class="icon-arrow-down"></i>
				<% end %>
			</th>
			<th>
				<%= sortable "created_at", "Date"%>
				<% if @direction=="asc" and @column=="created_at" %>
					<i class="icon-arrow-up"></i>
				<% elsif @direction=="desc" and @column=="created_at" %>
					<i class="icon-arrow-down"></i>
				<% end %>
			</th>
			<th> Actions </th>
		</tr>
	</thead>
	<tbody>
		<% @change.each do |change| %>
		<tr>
			<td>
				<% if change.add_remove == 1 %>
					Added
				<% elsif change.add_remove == 2 %>
					Used
				<% end %>
			</td>
			<td><%= change.count %></td>
			<td><%=change.created_at%></td>
			<td>
				<%= link_to " Delete",ingredient_change_path(@ingredient, change), :confirm => 'Are you sure?', :method => :delete %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/ingredients/edit.html.erb
<body>	
	<div class="row-fluid">
		<div class="span7 offset4">
			<legend>Edit Ingredient</legend>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6 offset3">
			<%= form_for(@ingredient, :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					Measure 1
				</label>
				<div class="controls">
					<%= f.text_field :measure1 %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					Measure 2
				</label>
				<div class="controls">
					<%= f.text_field :measure2 %>
				</div>
			</div>



			<div class="control-group">
				<label class="control-label">
					Measure 3
				</label>
				<div class="controls">
					<%= f.text_field :measure3 %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					Notes
				</label>
				<div class="controls">
					<%= f.text_area :note, :rows => 5 %>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<%= f.submit "Submit", :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>

<% end %>

app/views/ingredients/index.html.erb
<body>
	<div class="row">
		<div class="span7 offset2">
			<legend>Ingredient List</legend>
		</div>
	</div>

	<div class="row">
		<div class="span7 offset2">
			<%= search_form_for @search do |f| %>
			<div class="control-group">
				<div class="control-label">
					Measure 1
				</div>
				<div class="controls">
					<%= f.text_field :measure1_cont %>
				</div>
			</div>
			<div class="control-group">
				<div class="control-label">
					Measure 2
				</div>
				<div class="controls">
					<%= f.text_field :measure2_cont %>
				</div>
			</div>
			<div class="control-group">
				<div class="control-label">
					Measure 2
				</div>
				<div class="controls">
					<%= f.text_field :measure3_cont %>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<%= f.submit "Search", :class => "btn" %>
				</div>
			</div>
			<% end %>
		</div>
	</div>


	<div class="row">
	<div class="span7 offset2">
		<%= link_to "Add Ingredient", new_ingredient_path, {:class => 'btn btn-primary'} %>
	<p></p>
	</div>
</div>

	<div class="row">
		<div class="span7 offset2">
			<table class="table">
				<thread>
					<tr>
						<th>Dimensions</th>
						<th>Remaining</th>
						<th>Notes</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<% @ingredient.each do |ingredient| %>
					<tr>
						<td><%= link_to ingredient.measure1.to_s+" X "+ingredient.measure2.to_s+" X "+ingredient.measure3.to_s, ingredient %></td>
						<td><%=ingredient.total%></td>
						<td><%=ingredient.note%></td>
						<td>
							<%= form_for([ingredient, @change], :html=> {:class => 'form-inline'}) do |f| %>
								<%= f.text_field :count, :class => "input-small" %>
								<div class="input-append">
									<%= f.submit "Use", :class => "btn" %>
								</div>
							<% end %>
				</div>

						</td>							
					</tr>
					<% end %>
				</tbody>
			</table>
		<div>
	<div>
</body>

app/views/ingredients/new.html.erb
<body>	
	<div class="row-fluid">
		<div class="span7 offset4">
			<legend>New Ingredient</legend>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6 offset3">
			<%= form_for(@ingredient, :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					Measure 1
				</label>
				<div class="controls">
					<%= f.text_field :measure1 %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					Measure 2
				</label>
				<div class="controls">
					<%= f.text_field :measure2 %>
				</div>
			</div>



			<div class="control-group">
				<label class="control-label">
					Measure 3
				</label>
				<div class="controls">
					<%= f.text_field :measure3 %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					Notes
				</label>
				<div class="controls">
					<%= f.text_area :note, :rows => 5 %>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<%= f.submit "Submit", :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>

<% end %>

app/views/ingredients/show.html.erb
<div class="row">
	<div class="span7 offset2">
		<h2><%= @ingredient.measure1 %> X <%= @ingredient.measure2 %> X <%= @ingredient.measure3 %></h2>
		
		<h3>Remaining: <%= @ingredient.total %></h3>
		<h5><%= @ingredient.note %></h5>
	</div>
</div>

<div class="row">
	<div class="span7 offset2">
		<%= link_to "Return to Ingredients", ingredients_path, {:class => 'btn btn-primary'} %>
		<%= link_to "Add Change", new_ingredient_change_path(@ingredient), {:class => 'btn btn-primary'} %>
		<%= link_to "Edit", edit_ingredient_path(@ingredient), {:class => 'btn btn-primary'} %>
		<%= link_to " Delete",ingredient_path(@ingredient), {:confirm => 'Are you sure?', :class => 'btn btn-danger', :method => :delete}  %><td>
	<p></p>
	</div>
</div>

<div class="row">
		<div class="span7 offset2">
			<div id="changes">
				<%= render 'changes' %>
			</div>
		</div>
	</div>