config/routes.rb
ItaBite::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|ja/ do  

    resources :subcontractors 
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    
    match '/signup', to: 'users#new'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    resources :clients do
      resources :jobs
    end

    resources :machines do
      resources :employees do
        resources :approvals
      end
    end
    
    resources :employees do
      resources :machines do
        resources :approvals
      end
    end

    resources :jobs do
      resources :items
    end

    resources :items do
      resources :operations
      resources :rounds
      resources :squares
      resources :subcontracts
    end

    resources :ingredients do
      resources :changes
    end

  end

end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to :machine
  belongs_to :employee
  has_many :operations
  has_many :items
  attr_accessible :employee_id, :machine_id
end

app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :ingredient
  attr_accessible :count, :total, :add_remove, :created_at

  after_initialize :init

  def init
  	self.add_remove ||=2
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :jobs
  attr_accessible :name

    UNRANSACKABLE_ATTRIBUTES = ["created_at", "updated_at", "id"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :machines, :through => :approvals
  attr_accessible :first_name, :last_name, :machine_ids
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :changes
  attr_accessible :measure1, :measure2, :measure3, :note
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :blue_print_number, :completion, :job_id, :name, :pieces, :identification, :round_square
  has_many :subcontracts
  has_many :operations
  has_many :approvals, :through=>:operations
  has_many :rounds
  has_many :squares
  belongs_to :job
end

app/models/job.rb
class Job < ActiveRecord::Base
  DEFAULT_SEARCH_PARAMETER ={}
  attr_accessible :items_attributes, :actual, :billing, :contact, :description, :in_date, :name, :target, :client_id, :priority
  belongs_to :client
  has_many :items
  accepts_nested_attributes_for :items, :allow_destroy => true

  UNRANSACKABLE_ATTRIBUTES = ["description", "created_at", "updated_at", "client_id", "client"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :approvals, :dependent => :destroy
  has_many :employees, :through => :approvals
  attr_accessible :name, :notes, :machine_type, :employee_ids
end

app/models/misc_ingredient.rb
class MiscIngredient < ActiveRecord::Base
  attr_accessible :delivery_date, :description, :item_id, :material, :order_date, :pieces
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  attr_accessible :end, :notes, :start, :item_id, :machine_id, :employee_id, :approval_id
  belongs_to :item
  belongs_to :approval
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :delivery_date, :diameter, :item_id, :length, :material, :order_date, :pieces
  belongs_to :item
end

app/models/square.rb
class Square < ActiveRecord::Base
  attr_accessible :delivery_date, :item_id, :length, :material, :order_date, :pieces, :thickness, :width
  belongs_to :item
end

app/models/subcontract.rb
class Subcontract < ActiveRecord::Base
  belongs_to :item
  belongs_to :subcontractor
  attr_accessible :estimated, :in, :item_id, :notes, :out, :subcontractor_id
end

app/models/subcontractor.rb
class Subcontractor < ActiveRecord::Base
  attr_accessible :name
  has_many :subcontracts, :dependent=>:destroy
  has_many :items, :through=>:subcontracts
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :password, :password_confirmation, :email, :username
  has_secure_password
  
  before_save { |user| user.email=email.downcase}
  before_save :create_remember_token

  validates :username, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: 	true,
  					format: 	{ with: VALID_EMAIL_REGEX},
  					uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence:true 

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def new
		@job = Job.find(params[:job_id])
		@item=Item.new		
	end

	def create
		@job = Job.find(params[:job_id])
		@item = @job.items.new(params[:item])
		if @item.save
			redirect_to job_path(@job)
		else
			redirect_to job_path(@job)
		end
	end

	def update
		@job = Job.find(params[:job_id])
		@item = @job.items.find(params[:id]) 
		if @item.update_attributes(params[:item])
			redirect_to job_path(@job)
		else
			redirect_to job_path(@job)
		end
	end

	def edit
		@job = Job.find(params[:job_id])
		@item = @job.items.find(params[:id]) 
	end

	def destroy
		@job = Job.find(params[:job_id])
		@item = @job.items.find(params[:id]) 
		@item.destroy
		redirect_to job_path(@job)
	end

	def show
		if params[:job_id]
			@job = Job.find(params[:job_id])
			@item = @job.items.find(params[:id])
		else
			@item=Item.find(params[:id])
			@job=@item.job
		end
	end


end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_show_operation.html.erb
<%= link_to t(:operation_add),  new_item_operation_path(@item), {:class => 'btn btn-primary'} %>

<% if @item.operations[0]%>
	<table class="table">
		<thead>
			<tr>
				<th> <%=t :operation_process %> </th>
				<th> <%=t :machine_name %> </th>
				<th> <%=t :employee_name %> </th>
				<th> <%=t :operation_start %> </th>
				<th> <%=t :operation_end %> </th>
				<th> <%=t :notes %> </th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @item.operations.each do |operation| %>
			<tr>
				<td><%= operation.approval.machine.machine_type %></td>
				<td><%= operation.approval.machine.name %></td>
				<td><%= operation.approval.employee.last_name + operation.approval.employee.first_name %></td>
				<td><%= operation.start %></td>
				<td><% if operation.end? %>
						<%= operation.end %>
					<% else %>
						<%= form_for([@item, operation]) do |t| %>
							<%= t.hidden_field :end, :value => DateTime.now %>
							<%= t.submit t(:finish) %>
						<% end %>
					<% end %>
				</td>
				<td>
					<% operation.notes? ? "None" : "Notes" %>
				</td>
				<td><%= link_to t(:edit), edit_item_operation_path(@item, operation)%>
					<%= link_to t(:delete),item_operation_path(@item, operation), {:confirm => 'Are you sure?', :method => :delete} %>
				</td>
			<tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/items/_show_round.html.erb
<% @item.rounds.each do |round| %>
	<h4><%=t :ingredient %>: <%= round.material%>  <%=round.length%>mm X <%=round.diameter%>Ф - <%=round.pieces%>P </h4>
	<h5><%=t :ordered %>: <%= round.order_date %> </h5>
	<% if round.delivery_date? %>
		<h5><%=t :delivered %> <%= round.delivery_date %> </h5>
	<% else %>
		<%= form_for([@item, round]) do |t| %>
			<%= t.hidden_field :delivery_date, :value => Date.today %>
			<%= t.submit t(:delivery) %>
		<% end %>
	<% end %>
	<%= link_to t(:ingredient_edit),  edit_item_round_path(@item, round), {:class => 'btn btn-primary'} %>
	<%= link_to t(:ingredient_delete),item_round_path(@item, round), {:confirm => 'Are you sure?', :class => 'btn btn-danger', :method => :delete}  %>
<% end %>

app/views/items/_show_square.html.erb
<% @item.squares.each do |square| %>
	<h4><%=t :ingredient %>: <%= square.material%>  <%=square.thickness%>mm X <%=square.width%>mm X <%= square.length %> - <%=square.pieces%>P </h4>
	<h5><%=t :ordered %>: <%= square.order_date %> </h5>
	<% if square.delivery_date? %>
		<h5><%=t :delivered %> <%= square.delivery_date %> </h5>
	<% else %>
		<%= form_for([@item, square]) do |t| %>
			<%= t.hidden_field :delivery_date, :value => Date.today %>
			<%= t.submit t(:delivery) %>
		<% end %>
	<% end %>
	<%= link_to t(:ingredient_edit),  edit_item_square_path(@item, square), {:class => 'btn btn-primary'} %>
	<%= link_to t(:ingredient_delete),item_square_path(@item, square), {:confirm => 'Are you sure?', :class => 'btn btn-danger', :method => :delete}  %>
<% end %>

app/views/items/_show_subcontract.html.erb
<hr>
<%= link_to t(:subcontract_add),  new_item_subcontract_path(@item), {:class => 'btn btn-primary'} %>
<p></p>
<% if @item.subcontracts[0] %>
	<table class="table">
		<thead>
			<tr>
				<th> <%=t :subcontractor_name %> </th>
				<th> <%=t :subcontract_out_date %> </th>
				<th> <%=t :subcontract_estimate_date %> </th>
				<th> <%=t :subcontract_end_date %> </th>
				<th> <%=t :notes %> </th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @item.subcontracts.each do |subcontract| %>
			<tr>
				<td><%= subcontract.subcontractor.name %></td>
				<td><%= subcontract.out %></td>
				<td><%= subcontract.estimated %></td>
				<td><% if subcontract.in? %>
						<%= subcontract.in %>
					<% else %>
						<%= form_for([@item, subcontract]) do |t| %>
							<%= t.hidden_field :in, :value => DateTime.now %>
							<%= t.submit t(:finish) %>
						<% end %>
					<% end %>
				</td>
				<td>
					<%= subcontract.notes %>
				</td>
				<td><%= link_to t(:edit), edit_item_subcontract_path(@item, subcontract)%>
					<%= link_to t(:delete),item_subcontract_path(@item, subcontract), {:confirm => 'Are you sure?', :method => :delete} %>
				</td>
			<tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/items/edit.html.erb
<div class="row-fluid">
		<div class="span7 offset4">
			<legend><%=t :item_edit %></legend>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6 offset3">
			<%= form_for([@job, @item], :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					ID
				</label>
				<div class="controls">
					<%= f.text_field :identification %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :item_name %>
				</label>
				<div class="controls">
					<%= f.text_field :name %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :pieces %>
				</label>
				<div class="controls">
					<%= f.text_field :pieces %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :item_bp %>
				</label>
				<div class="controls">
					<%= f.text_field :blue_print_number %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :round_square %>
				</label>
				<div class="controls">
					<%= f.text_field :round_square %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :item_complete %>
				</label>
				<div class="controls">
					<%= f.date_select :completion, :start_year => Time.now.year, :end_year => Time.now.year + 1, :order => [:year, :month, :day], :include_blank => true%>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<%= f.submit t(:edit), :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>

<% end %>

app/views/items/new.html.erb
<body>
	<div class="row">
		<div class="span7 offset4">
			<legend><%=t :item_add %></legend>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6 offset3">
			<%= form_for([@job, @item], :html=> {:class => 'form-horizontal'}) do |f| %>

			<div class="control-group">
				<label class="control-label">
					ID
				</label>
				<div class="controls">
					<%= f.text_field :identification %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :item_name %>
				</label>
				<div class="controls">
					<%= f.text_field :name %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :pieces %>
				</label>
				<div class="controls">
					<%= f.text_field :pieces %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :item_bp %>
				</label>
				<div class="controls">
					<%= f.text_field :blue_print_number %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label">
					<%=t :round_square %>
				</label>
				<div class="controls">
					<%= f.text_field :round_square %>
				</div>
			</div>

			
			<div class="control-group">
				<div class="controls">
					<%= f.submit t(:submit), :class => "btn" %>
				</div>
			</div>
		</div>
	<div>
</body>

<% end %>

app/views/items/show.html.erb
<body>
	<div class="row">
		<div class="span10 offset1">
			<h2> <%= @item.identification %> <%=link_to @job.name, @job%> <%= @item.pieces %>P</h2>
			<h3> <%= @item.name %> (<%= @item.blue_print_number %>) </h3>

			<%= link_to t(:item_edit),  edit_job_item_path(@job, @item), {:class => 'btn btn-primary'} %>
			<%= link_to t(:item_delete),job_item_path(@job, @item), {:confirm => 'Are you sure?', :class => 'btn btn-danger', :method => :delete}  %>
			<hr>
		</div>
	</div>

	<div class="row">
		<div class="span10 offset1">
			<% if @item.rounds[0] %>
				<%= render "show_round" %>
				<hr>
			<% elsif @item.squares[0] %>
				<%= render "show_square" %>
				<hr>
			<% elsif @item.round_square == "Round" || @item.round_square == "丸" %>
					<%= link_to t(:ingredient_add),  new_item_round_path(@item), {:class => 'btn btn-primary'} %>
			<% else @item.round_square == "Square" || @item.round_square == "角" %>
					<%= link_to t(:ingredient_add),  new_item_square_path(@item), {:class => 'btn btn-primary'} %>
			<% end %>
			<hr>
		</div>
	</div>

	<div class ="row">
		<div class="span10 offset1">
			<%= render "show_operation" %>
		</div>
	</div>

	<div class ="row">
		<div class="span10 offset1">
			<%= render "show_subcontract" %>
		</div>
	</div>